
-- EXERCICIO: Escreva em PL/SQL
--A)

DROP TABLE VENDASMES;
CREATE TABLE VENDASMES(
    COD_VEND  INTEGER,
    NOME_VEND    VARCHAR(50),
    MES_VEND INTEGER,
    TOTAL_VEND INTEGER
);
create or replace PROCEDURE SP_INSERE_VENDASMES(
    NOMEVEND IN VENDASMES.NOME_VEND%TYPE,
    MESVEND IN VENDASMES.MES_VEND%TYPE,
    TOTALVEND IN VENDASMES.TOTAL_VEND%TYPE)
    AS
BEGIN
    DELETE FROM VENDASMES;
    INSERT INTO VENDASMES(NOME_VEND,MES_VEND,TOTAL_VEND)
    SELECT DISTINCT VENDEDOR.NOMEVEND,
                EXTRACT(MONTH FROM PEDIDO.DATA) AS MESVEND,
                SUM(PRODUTO.VALUNIT) AS TOTALVEND
    FROM VENDEDOR INNER JOIN 
        (PEDIDO INNER JOIN 
        (ITEMPED INNER JOIN PRODUTO
        ON ITEMPED.CODPROD = PRODUTO.CODPROD)
        ON PEDIDO.NUMPED = ITEMPED.NUMPED)
        ON VENDEDOR.CODVEND = PEDIDO.CODVEND
        GROUP BY VENDEDOR.NOMEVEND,
                 EXTRACT(MONTH FROM PEDIDO.DATA)
        ORDER BY EXTRACT(MONTH FROM PEDIDO.DATA);
COMMIT;
END SP_INSERE_VENDASMES;

--B)
CREATE OR REPLACE PROCEDURE SP_ATUALIZA_VENDASMES
    (NOMEVEND OUT VENDASMES.NOME_VEND%TYPE,
     MESVEND OUT VENDASMES.MES_VEND%TYPE,
     TOTALMES OUT VENDASMES.TOTAL_VEND%TYPE,
     DATA OUT PEDIDO.DATA%TYPE) AS
BEGIN
    UPDATE VENDASMES
    SET NOME_VEND = NOMEVEND,
        MES_VEND = EXTRACT(MONTH FROM DATA),
        TOTAL_VEND = TOTALMES
    WHERE MES_VEND = EXTRACT(MONTH FROM DATA);
END SP_ATUALIZA_VENDASMES;

--C)

ALTER TABLE CLIENTE ADD TOTALCOMPRAS FLOAT;

CREATE OR REPLACE FUNCTION RETORNA_TOTAL_PED
    (CODCLIENTE CLIENTE.CODCLI%TYPE)
    RETURN FLOAT 
IS
    TOTALPEDIDOS FLOAT;
BEGIN
        SELECT SUM(PRODUTO.VALUNIT) INTO TOTALPEDIDOS
        FROM PRODUTO, ITEMPED
        WHERE PRODUTO.CODPROD = ITEMPED.CODPROD;
        RETURN TOTALPEDIDOS;
END;

--D)
create or replace FUNCTION INSERE_PEDIDO_ITEMPED
    (NUM_PED NUMBER,
    PRAZO_ENTR NUMBER,
    COD_CLI NUMBER,
    COD_VEND NUMBER,
    DATA_PED DATE,
    COD_PROD NUMBER,
    QUANT_ITEM NUMBER)
    RETURN VARCHAR2
IS
    COND BOOLEAN := FALSE;
    TEXT VARCHAR2(5) := 'OK';
BEGIN
    CASE NOT COND
    WHEN NUM_PED != NULL AND
         PRAZO_ENTR != NULL AND
         COD_CLI != NULL AND
         COD_VEND != NULL AND
         DATA_PED != NULL
    THEN
        INSERT INTO PEDIDO(NUMPED,PRAZOENTR,CODCLI,CODVEND,DATA)
        VALUES (NUM_PED,PRAZO_ENTR,COD_CLI,COD_VEND,DATA_PED);
    WHEN NUM_PED != NULL AND
         COD_PROD != NULL AND
         QUANT_ITEM != NULL
    THEN
        INSERT INTO ITEMPED(NUMPED,CODPROD,QUANT)
        VALUES (NUM_PED,COD_PROD,QUANT_ITEM);
    ELSE 
        DBMS_OUTPUT.PUT_LINE('Exception Message:'||SQLERRM);
        DBMS_OUTPUT.PUT_LINE('Linha: ' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
    END CASE;
RETURN TEXT;
END;



















 
    