


CREATE ROLE ALUNO;
GRANT create session, create table, create view, create sequence TO ALUNO;
GRANT create any trigger, create any procedure TO ALUNO;
grant CREATE USER, DROP USER TO ALUNO WITH admin OPTION;
grant CREATE ROLE TO ALUNO WITH admin OPTION;
grant ALTER USER TO ALUNO WITH admin OPTION;
grant GRANT ANY ROLE TO ALUNO WITH admin OPTION;

--TAREFA A

CREATE USER brunoolliver141 IDENTIFIED BY 703897 DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP QUOTA 100M ON USERS;
GRANT ALUNO TO brunoolliver141;

REVOKE DELETE ON ALUNO FROM brunoolliver141;