--TAREFA A

CREATE TABLE CLIENTE (
    CODIGO INTEGER PRIMARY KEY,
    NOME CHAR(40) NOT NULL
);

GRANT INSERT, SELECT, UPDATE ON CLIENTE TO brunoolliver141;


INSERT INTO CLIENTE VALUES(1,'NEYMAR');
INSERT INTO CLIENTE VALUES(2,'COUTINHO');
INSERT INTO CLIENTE VALUES(3,'MARCELO');
INSERT INTO CLIENTE VALUES(4,'ALISSON');
INSERT INTO CLIENTE VALUES(5,'GABRIEL JESUS');
INSERT INTO CLIENTE VALUES(6,'ROBERTO FIRMINO');
INSERT INTO CLIENTE VALUES(7,'FREDERICO');
INSERT INTO CLIENTE VALUES(8,'DOUGLAS COSTA');
INSERT INTO CLIENTE VALUES(9,'DANILO SILVA');
INSERT INTO CLIENTE VALUES(10,'FERNANDINHO');
INSERT INTO CLIENTE VALUES(11,'TAISON');

SELECT * FROM CLIENTE;

UPDATE CLIENTE SET NOME = 'CASSIO RAMOS'
WHERE  CODIGO = 4;

DELETE FROM CLIENTE
WHERE NOME = 'NEYMAR';

--TAREFA B

CREATE TABLE ITENS (
    CODIGO INTEGER PRIMARY KEY,
    ITEM CHAR(50) NOT NULL
);

CREATE ROLE CAIXA;
GRANT INSERT, SELECT ON ITENS TO CAIXA;

CREATE ROLE GERENTE;
GRANT SELECT, UPDATE,  DELETE ON ITENS TO GERENTE;

DROP USER MARIA;
DROP USER JOAO;

CREATE USER MARIA IDENTIFIED BY 123;
GRANT CAIXA TO MARIA;

CREATE USER JOAO IDENTIFIED BY 123;
GRANT CAIXA TO  JOAO;

CREATE USER JOSE IDENTIFIED BY 123;
GRANT GERENTE TO  JOSE;

GRANT create session, create table, create view, create sequence TO CAIXA;
GRANT create session, create table, create view, create sequence TO GERENTE;


INSERT INTO ITENS VALUES (1,'SABAO EM BARRA');
INSERT INTO ITENS VALUES (2,'SABONETE');
INSERT INTO ITENS VALUES (3,'DETTERGENTE');
INSERT INTO ITENS VALUES (4,'SABAO EM PO');

SELECT * FROM ITENS;

UPDATE ITENS SET NOME = 'DETERGENTE' WHERE CODIGO = 3;

SELECT * FROM ITENS;

